#Download Manager Configuration
#Tue May 05 11:40:40 EEST 2026
download.directory=E\:\\Games
download.maxSpeed=10240000
p2p.central.port=5000
p2p.directory=E\:\\Games
p2p.port=5006
p2p.serverAddress=127.0.0.1
