#Download Manager Configuration
#Mon Dec 30 16:18:13 EET 2024
p2p.serverAddress=127.0.0.1
p2p.central.port=5000
download.directory=D\:\\DownloadTest
download.maxSpeed=10240000
p2p.port=5006
p2p.directory=D\:\\DownloadTest
